const base = "animate__animated";
const animations = {
  bounce: `${base} animate__bounce`,
  pulse: `${base} animate__pulse`,
  backInDown: `${base} animate__backInDown`,
  backInLeft: `${base} animate__backInLeft`,
  backInRight: `${base} animate__backInLeft`,
  backInUp: `${base} animate__backInUp`,
  bounceIn: `${base} animate__bounceIn`,
  bounceInDown: `${base} animate__bounceInDown`,
  bounceInleft: `${base} animate__bounceInLeft`,
  bounceInRight: `${base} animate__bounceInRight`,
  bounceInUp: `${base} animate__bounceInUp`,
  fadeIn: `${base} animate__fadeIn`,
  fadeInDown: `${base} animate__fadeInDown`,
  fadeInLeft: `${base} animate__fadeInLeft`,
  fadeInRight: `${base} animate__fadeInRight`,
  fadeInUp: `${base} animate__fadeInUp`,
  fadeInTopRight: `${base} animate__fadeInTopRight`,
  fadeInTopLeft: `${base} animate__fadeInTopLeft`,
  fadeOutRight: `${base} animate__fadeOutRight`,
  fadeOutLeft: `${base} animate__fadeOutLeft`,
  fadeInBottomRight: `${base} animate__fadeInBottomRight`,
  fadeInBottomLeft: `${base} animate__fadeInBottomLeft`,
  flip: `${base} animate__flipInX`,
  zoomIn: `${base} animate__zoomIn`,
  slideInDown: `${base} animate__slideInDown`,
  slideInLeft: `${base} animate__slideInLeft`,
  slideInRight: `${base} animate__slideInRight`,
  slideInUp: `${base} animate__slideInUp`,
  zoomOut: `${base} animate__zoomOut`,
  fadeOut: `${base} animate__fadeOut`,
  fadeOutDown: `${base} animate__fadeOutDown`,
  fadeOutUp: `${base} animate__fadeOutUp animate__faster animate__delay-0s`,
  slideOutLeft: `${base} animate__slideOutLeft animate__faster animate__delay-0s`,
  slideOutDown: `${base} animate__slideOutDown animate__faster animate__delay-0s`,
};

export default animations;
